import { useState, useCallback, useEffect } from "react";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import { createId } from "@/lib/id";
import {
  createSupabaseOutfit,
  deleteSupabaseOutfit,
  getOrCreateSupabaseUserId,
  listSupabaseOutfits,
} from "@/services/outfitsSupabase";

// Represents an item generated by the AI, which can be added to the canvas.
export interface GeneratedItem {
  id: string;
  category: "top" | "trousers" | "shoes";
  imageUrl: string;
  prompt: string;
  createdAt: string;
}

// Represents an item placed on the canvas editor
export interface CanvasItem {
  id: string;
  imageUrl: string;
  category: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  zIndex: number; // Layer order - higher values appear on top
}

// Represents a saved outfit, which includes metadata and the items on the canvas when the user saved it.
export interface Outfit {
  id: string;
  name: string;
  timestamp: string;
  userPhoto: string | null;
  canvasItems: CanvasItem[];
}

// Custom hook to manage outfits, which are saved in localStorage. Provides functions to save, delete and load outfits.
const STORAGE_KEY = "dressify-outfits";

function readLocalOutfits(): Outfit[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

function writeLocalOutfits(outfits: Outfit[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(outfits));
}

export function useOutfits() {
  const [outfits, setOutfits] = useState<Outfit[]>(() => readLocalOutfits());
  const [isLoading, setIsLoading] = useState(true);
  const [isCloudSyncEnabled, setIsCloudSyncEnabled] = useState(false);
  const [syncError, setSyncError] = useState<string | null>(null);
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    let authUnsubscribe: (() => void) | null = null;

    const initialize = async () => {
      if (mounted) {
        setIsLoading(true);
      }

      if (!isSupabaseConfigured) {
        if (mounted) {
          setIsCloudSyncEnabled(false);
          setUserId(null);
          setIsLoading(false);
        }
        return;
      }

      try {
        const resolvedUserId = await getOrCreateSupabaseUserId();
        if (!mounted) return;

        if (!resolvedUserId) {
          setIsCloudSyncEnabled(false);
          setUserId(null);
          setSyncError(
            "Supabase is configured but no auth session is available. Data is being saved locally only.",
          );
          setIsLoading(false);
          return;
        }

        const remoteOutfits = await listSupabaseOutfits(resolvedUserId);
        if (!mounted) return;

        setUserId(resolvedUserId);
        setOutfits(remoteOutfits);
        setIsCloudSyncEnabled(true);
        setSyncError(null);
      } catch (error) {
        if (!mounted) return;
        const message = error instanceof Error ? error.message : "Unknown Supabase error";
        setIsCloudSyncEnabled(false);
        setUserId(null);
        setSyncError(`Supabase sync failed (${message}). Using local mode.`);
      } finally {
        if (mounted) {
          setIsLoading(false);
        }
      }
    };

    void initialize();

    if (supabase) {
      const { data } = supabase.auth.onAuthStateChange(() => {
        void initialize();
      });
      authUnsubscribe = () => data.subscription.unsubscribe();
    }

    return () => {
      mounted = false;
      authUnsubscribe?.();
    };
  }, []);

  const saveOutfit = useCallback(
    async (name: string, userPhoto: string | null, canvasItems: CanvasItem[]) => {
      if (isCloudSyncEnabled && userId) {
        const outfit = await createSupabaseOutfit(userId, name, canvasItems);
        setOutfits((prev) => [outfit, ...prev]);
        return outfit;
      }

      const outfit: Outfit = {
        id: createId(),
        name,
        timestamp: new Date().toISOString(),
        userPhoto,
        canvasItems,
      };
      setOutfits((prev) => {
        const updated = [outfit, ...prev];
        writeLocalOutfits(updated);
        return updated;
      });
      return outfit;
    },
    [isCloudSyncEnabled, userId]
  );

  const deleteOutfit = useCallback(
    async (id: string) => {
      if (isCloudSyncEnabled && userId) {
        await deleteSupabaseOutfit(userId, id);
        setOutfits((prev) => prev.filter((o) => o.id !== id));
        return;
      }

      setOutfits((prev) => {
        const updated = prev.filter((o) => o.id !== id);
        writeLocalOutfits(updated);
        return updated;
      });
    },
    [isCloudSyncEnabled, userId]
  );

  const loadOutfit = useCallback(
    (id: string) => outfits.find((o) => o.id === id) || null,
    [outfits]
  );

  return {
    outfits,
    saveOutfit,
    deleteOutfit,
    loadOutfit,
    isLoading,
    isCloudSyncEnabled,
    syncError,
  };
}
