import { useState, useCallback } from "react";

// Represents an item generated by the AI, which can be added to the canvas.
export interface GeneratedItem {
  id: string;
  category: "top" | "trousers" | "shoes";
  imageUrl: string;
  prompt: string;
  createdAt: string;
}

// Represents an item placed on the canvas editor
export interface CanvasItem {
  id: string;
  imageUrl: string;
  category: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
}

// Represents a saved outfit, which includes metadata and the items on the canvas when the user saved it.
export interface Outfit {
  id: string;
  name: string;
  timestamp: string;
  userPhoto: string | null;
  canvasItems: CanvasItem[];
}

// Custom hook to manage outfits, which are saved in localStorage. Provides functions to save, delete and load outfits.
const STORAGE_KEY = "dressify-outfits";

export function useOutfits() {
  // Loads saved outfits once (initial state)
  const [outfits, setOutfits] = useState<Outfit[]>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  const saveOutfit = useCallback(
    (name: string, userPhoto: string | null, canvasItems: CanvasItem[]) => {
      const outfit: Outfit = {
        id: crypto.randomUUID(),
        name,
        timestamp: new Date().toISOString(),
        userPhoto,
        canvasItems,
      };
      const updated = [outfit, ...outfits];
      setOutfits(updated);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
      return outfit;
    },
    [outfits]
  );

  const deleteOutfit = useCallback(
    (id: string) => {
      const updated = outfits.filter((o) => o.id !== id);
      setOutfits(updated);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    },
    [outfits]
  );

  const loadOutfit = useCallback(
    (id: string) => outfits.find((o) => o.id === id) || null,
    [outfits]
  );

  return { outfits, saveOutfit, deleteOutfit, loadOutfit };
}
